### ISSUE TITLE
AUR status

### ISSUE THREAD

**Issue by AladW** [M-Reimer/repo-make#1]
Hi,

It seems there's an AUR package for this but it has been orphaned for the last six months. Is this project still active? If so, would you mind maintaining the AUR package?

https://aur.archlinux.org/packages/repo-make/#comment-720823

Cheers

**Comment by M-Reimer** [comment]
The project is still active, but is it really a good idea to make it too easily available? The idea is that, for autobuilding, a dedicated virtual machine is set up. "repo-make" will install, update and uninstall packages depending on the build requirements. It is NOT recommended to install repo-make on any productive machine or machine you use for your daily work!

I myself use "Virtual Box" for my build machine and for the vdr4arch project we have something working with "Docker" on a V-Server to do the auto build whenever a GIT commit is done.

**Comment by M-Reimer** [comment]
Seems like repo-make was deleted from AUR recently.

I still think it shouldn't be too simple to install repo-make. It is meant to run inside some chroot container, Docker or virtual machine so nothing gets destroyed if the automatic install/uninstall routines fail in some way. I've also added a warning now (in hope people will call it as regular user first):
https://github.com/M-Reimer/repo-make/blob/master/repo-make#L77-L81

But I will create a new release soon and upload a finished Arch package to the Releases page in case someone wants to just install it (into a dedicated build environment, of course).
